name: open_file_manager
description: A flutter plugin to open default file manager app. on an Android, it opens Download/Recent folder on file manager app. on iOS, it opens app's document folder in Files app.
version: 1.0.2
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/open_file_manager
issue_tracker: https://github.com/nayanAubie/open_file_manager/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aubergine.open_file_manager
        pluginClass: OpenFileManagerPlugin
      ios:
        pluginClass: OpenFileManagerPlugin
