name: multi_frc
description: "Multiple Firebase Remote Config Helper"
version: 0.0.3
homepage: https://github.com/jabardigitalservice/flutter-packages/tree/main/multi_frc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.11.0
  firebase_remote_config: ^6.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
