name: multi_frc
description: "Multiple Firebase Remote Config Helper"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
