/// Database for all the extensions

const Map<String, String> database = {
  'audio/aac': '.aac',
  'image/avif': '.avif',
  'video/x-msvideo': '.avi',
  'application/octet-stream': '.bin',
  'image/bmp': '.bmp',
  'text/css': '.css',
  'text/csv': '.csv',
  'application/msword': '.doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
      '.docx',
  'application/vnd.ms-fontobject': '.eot',
  'application/epub+zip': '.epub',
  'application/gzip': '.gz',
  'image/gif': '.gif',
  'text/html': '.html',
  'image/vnd.microsoft.icon': '.ico',
  'application/java-archive': '.jar',
  'image/jpeg': '.jpeg',
  'text/javascript': '.js',
  'application/json': '.json',
  'audio/midi': '.mid',
  'audio/x-midi': '.midi',
  'audio/mpeg': '.mp3',
  'video/mp4': '.mp4',
  'video/mpeg': '.mpeg',
  'audio/ogg': '.oga',
  'video/ogg': '.ogv',
  'font/otf': '.otf',
  'image/png': '.png',
  'application/pdf': '.pdf',
  'application/x-httpd-php': '.php',
  'application/vnd.ms-powerpoint': '.ppt',
  'application/vnd.rar': '.rar',
  'application/rtf': '.rtf',
  'application/x-sh': '.sh',
  'image/svg+xml': '.svg',
  'application/x-tar': '.tar',
  'image/tiff': '.tiff',
  'video/mp2t': '.ts',
  'font/ttf': '.ttf',
  'text/plain': '.txt',
  'audio/wav': '.wav',
  'video/webm': '.webm',
  'image/webp': '.webp',
  'font/woff': '.woff',
  'font/woff2': '.woff2',
  'application/xhtml+xml': '.xhtml',
  'application/vnd.ms-excel': '.xls',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
  'application/xml': '.xml',
  'application/zip': '.zip',
};
