name: Performance Monitoring

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./performance_monitoring
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze